src/Web/CSGOBeast.Web/ViewModels/Items/ItemDetailsViewModel.cs
namespace CSGOBeast.Web.ViewModels.Items
{
    using CSGOBeast.Data.Models;
    using CSGOBeast.Web.Infrastructure.Mapping;

    public class ItemDetailsViewModel : IMapFrom<Item>
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ImageLink { get; set; }

        public decimal Price { get; set; }

        public ItemQuality Quality { get; set; }

        public GroupType GroupType { get; set; }

        public WeaponType WeaponType { get; set; }

        public ItemClassification Classification { get; set; }

        public BuyModel BuyModel => new BuyModel { ItemId = this.Id };

        public SellModel SellModel => new SellModel { ItemId = this.Id };
    }
}

src/Web/CSGOBeast.Web/ViewModels/Shared/PageableModel.cs
namespace CSGOBeast.Web.ViewModels.Shared
{
    public abstract class PageableModel
    {
        public int CurrentPage { get; set; }

        public int TotalPages { get; set; }
    }
}

src/Web/CSGOBeast.Web/Controllers/ItemsController.cs
namespace CSGOBeast.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Services.Data;
    using ViewModels.Items;

    [Authorize]

    public class ItemsController : BaseController
    {
        private IItemsService items;

        public ItemsController(IItemsService items)
        {
            this.items = items;
        }

        public ActionResult Details(int id)
        {
            var item = this.items.GetById(id);
            var viewModel = this.Mapper.Map<ItemDetailsViewModel>(item);

            return this.View(viewModel);
        }
    }
}

src/Web/CSGOBeast.Web/Controllers/ShopController.cs
namespace CSGOBeast.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Common;
    using Infrastructure.Mapping;
    using Microsoft.AspNet.Identity;
    using Services.Data;
    using ViewModels.Shop;

    public class ShopController : BaseController
    {
        private const int DefaultPageSize = 12;
        private IItemsService items;
        private IUsersService users;

        public ShopController(IItemsService items, IUsersService users)
        {
            this.items = items;
            this.users = users;
        }

        public ActionResult Items(int id = 1, string name = null, string minPrice = null, string maxPrice = null, string groupType = null, string quality = null, string weaponType = null, string classification = null, string order = null)
        {
            var viewModel = new ShopViewModel();
            if (this.User.Identity.IsAuthenticated)
            {
                var userId = this.User.Identity.GetUserId();
                var user = this.users.GetById(userId);
                var userViewModel = this.Mapper.Map<ShopUserViewModel>(user);
                viewModel.User = userViewModel;
            }

            var items = this.Cache.Get(
                GlobalConstants.ItemsInfoCache,
                () => this.items.GetPublic().To<ShopItemViewModel>().ToList(),
                30);
            if (order != null)
            {
                items = order == "highestprice" ? items.OrderByDescending(x => x.Price).ToList() : items = items.OrderBy(x => x.Price).ToList();
            }

            var itemsToDisplay = items
                .Where(x => string.IsNullOrEmpty(name) ? true : x.Name.ToLower().Contains(name.ToLower()))
                .Where(x => string.IsNullOrEmpty(minPrice) ? true : (x.Price >= decimal.Parse(minPrice)))
                .Where(x => string.IsNullOrEmpty(maxPrice) ? true : (x.Price <= decimal.Parse(maxPrice)))
                .Where(x => string.IsNullOrEmpty(groupType) ? true : ((int)x.GroupType == int.Parse(groupType)))
                .Where(x => string.IsNullOrEmpty(quality) ? true : ((int)x.Quality == int.Parse(quality)))
                .Where(x => string.IsNullOrEmpty(weaponType) ? true : ((int)x.WeaponType == int.Parse(weaponType)))
                .Where(x => string.IsNullOrEmpty(classification) ? true : ((int)x.Classification == int.Parse(classification)))
                .ToList();

            var page = id;
            var allItemsCount = itemsToDisplay.Count();
            var itemsToSkip = (page - 1) * DefaultPageSize;
            var totalPages = (int)Math.Ceiling(allItemsCount / (decimal)DefaultPageSize);

            itemsToDisplay = itemsToDisplay
                .Skip(itemsToSkip)
                .Take(DefaultPageSize)
                .ToList();

            viewModel.Items = itemsToDisplay;
            viewModel.CurrentPage = page;
            viewModel.TotalPages = totalPages;

            return this.View(viewModel);
        }
    }
}

src/Web/CSGOBeast.Web/Views/Shared/_ItemDetails.cshtml
@model CSGOBeast.Web.ViewModels.Shop.ShopItemViewModel
<div class="col-lg-3 col-md-6 text-center">
    <div class="well result-box nomargin">
        <h3><a href="/Items/Details/@Model.Id">@Model.Name</a></h3>

        <div class="quality color-covert">
            <p class="nomargin">@Model.Classification.ToString()</p>
        </div>
        <a href="@Model.ImageLink"><img class="img-responsive center-block" src="@Model.ImageLink" alt="@Model.Name"></a>
        <div class="quality">
            <p class="nomargin"><span class="text-success">@Model.Quality.ToString()</span></p>
        </div>
        <div class="price">
            <p class="nomargin"><span class="price-st">@Model.Price $</span></p>
        </div>
        <div class="details-link">
            <p class="nomargin"><a class="btn btn-success btn-xs" href="/Items/Details/@Model.Id">@Model.Name Skin &amp; Price Details</a></p>
        </div>
    </div>
</div>

src/Web/CSGOBeast.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CSGOBeast</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="loginLink" href="@Url.Action("Index", "Home", routeValues:new { area = string.Empty })">
                    <img class="home-logo-btn" src="~/Content/Images/logo.png" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Store", "Items", "Shop", routeValues: new { area = string.Empty }, htmlAttributes: new { @class = "" })
                    </li>
                    <li>@Html.ActionLink("CoinFlip", "Current", "CoinFlips", new { area = "Games" }, null)</li>
                </ul>
                @*<ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Games", "Index", "Home", new { area = string.Empty }, null)</li>
                    </ul>*@
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CSGOBeast</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @if (Request.IsAuthenticated)
    {
        @Scripts.Render("~/bundles/steamJs")
    }
    @RenderSection("scripts", required: false)
</body>
</html>

src/Web/CSGOBeast.Web/Views/Shared/_SearchFilters.cshtml
@model CSGOBeast.Web.ViewModels.Shop.ShopViewModel
<div class="row">
    <div class="col-md-12 well">
        <form method="GET" style="text-align:center;">
            <input id="search-name" name="name" placeholder="Filter by name or wear." class="filter-skins-store" style="width:200px" type="text">
            <input id="search-min-price" step="0.01" name="minprice" placeholder="Min. price" style="width:80px" type="number">
            <input id="search-max-price" step="0.01" name="maxprice" placeholder="Max. price" style="width:80px" type="number">
            @Html.EnumDropDownListFor(model => model.GroupType, "group", htmlAttributes: new { id = "item-group-type" })
            @Html.EnumDropDownListFor(model => model.Quality, "quality", htmlAttributes: new { id = "item-quality-type" })
            @Html.EnumDropDownListFor(model => model.WeaponType, "wep", htmlAttributes: new { id = "item-weapon-type" })
            @Html.EnumDropDownListFor(model => model.Classification, "rarity", htmlAttributes: new { id = "item-classification-type" })
            <select id="order-by" name="order" style="color:black;">
                <option value="highestprice">Highest Price</option>
                <option value="lowestprice">Lowest Price</option>
            </select>
            <input type="submit" id="search-submit" value="Search" class="btn btn-success btn-xs">
        </form>
    </div>
</div>